### ISSUE TITLE
Webpack3 support

### ISSUE THREAD

**Issue by Ailrun** [torifat/flowtype-loader#12]
Now webpack3 is [officially released](https://medium.com/webpack/webpack-3-official-release-15fd2dd8f07b).
Is there any plan to support it?

**Comment by raultomescu** [comment]
+1. We probably just need to update the peerDep.

**Comment by Ailrun** [comment]
And know what?
[They](https://webpack.js.org/guides/migrating/) said,
> version 4 is on the horizon. 

Please update this repo... TT

**Comment by torifat** [comment]
Sorry, I somehow missed it. And, didn't realize people are still using it 🤦‍♂️

I will update it soon.
