### ISSUE TITLE
how`bout move FLOW-BIN into DEPENDENCIES instead of DEVDEPENDENCIES in package.json?

### ISSUE THREAD

**Issue by VaJoy** [torifat/flowtype-loader#7]
then makes `flow-bin` to be installed automatically

**Comment by VaJoy** [comment]
oh it`s weird that `npm` ignored the `package.json` to install `flow-bin`... :(

**Comment by VaJoy** [comment]
oh IMO, it might be better to put `flow-bin` into `dependencies` but not `devDependencies`

**Comment by jamiebuilds** [comment]
If anything it should be `peerDependencies`, but then it's gonna have to be updated with every release which is quite frequent

**Comment by VaJoy** [comment]
alright :)
